# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Thinny
tagline:	'blog'
description:	'My personal blog.'
url:		http://keepcalminblog.github.io

author:
  name:		'Ian Camporez Brunelli'
  url:		https://keepcalminblog.github.io

paginate:	3

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

    
menu:
  - title:	Home
    url:	http://keepcalminblog.github.io
    
copyright:
  author:	keepcalminblog
  url:		http://keepcalminblog.github.io
  type_title:	Some rights reserved
  type_url:	http://keepcalminblog.github.io
