# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink:  http://keepcalminblog.github.io

# Setup
title:    Thinny
tagline:  'blog'
description:  'My personal blog.'
url:    http://keepcalminblog.github.io

author:
  name:   'Ian Camporez Brunelli'
  url:    https://google.com

paginate: 5

# Custom vars
icon:   /assets/images/icon.png
cover:    /assets/images/cover.jpg

menu:
  - title:  Home
    url:  /
    
copyright:
  author: Camporez
  url:    http://keepcalminblog.github.io
  type_title: Some rights reserved
  type_url: http://keepcalminblog.github.io
