# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink:

# Setup
title:    Онлайн казино - советы
tagline:  'blog'
description:  'Все советы о том как игарть в покер или онлайн казино'
url:    http://www.zvezda-langepasa.com
baseurl: /

author:
  name:   'Fishka'
  url:    http://www.zvezda-langepasa.com

paginate: 10

# Custom vars
icon:   /assets/images/icon.png
cover:    /assets/images/cover.jpg

menu:
  - title:  Главная
    url:  /

copyright:
  author: Fishka
  url:    http://www.zvezda-langepasa.com
  
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-123-456          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-minifier"
  - "jekyll-analytics"

plugins:
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-analytics
