# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink:  /blog/:title

# Setup
title:    Thinny
tagline:  'blog'
description:  'My personal blog.'
url:    http://keepcalminblog.github.io

author:
  name:   'Ian Camporez Brunelli'
  url:    https://google.com

paginate: 5

# Custom vars
icon:   /assets/images/icon.png
cover:    /assets/images/cover.jpg

social:
  - icon: twitter
    url:  https://twitter.com/
    desc: Follow me on twitter

  - icon: github
    url:  https://github.com
    desc: Fork me on github

  - icon: googleplus-alt
    url:  https://google.com/
    desc: Add me on google+

  - icon: feed
    url:  http://camporez.com/atom.xml
    desc: Subscribe to my feed
    
menu:
  - title:  Home
    url:  /
    
copyright:
  author: Camporez
  url:    http://keepcalminblog.github.io
  type_title: Some rights reserved
  type_url: http://keepcalminblog.github.io
