# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink:  http://keepcalminblog.github.io

# Setup
title:    Онлайн казино - советы
tagline:  'blog'
description:  'Все советы о том как игарть в покер или онлайн казино'
url:    http://keepcalminblog.github.io

author:
  name:   'Fishka'
  url:    https://google.com

paginate: 10

# Custom vars
icon:   /assets/images/icon.png
cover:    /assets/images/cover.jpg

menu:
  - title:  Home
    url:  /
    
copyright:
  author: Fishka
  url:    http://keepcalminblog.github.io
  type_title: Some rights reserved
  type_url: http://keepcalminblog.github.io
