# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink:  http://http://www.zvezda-langepasa.com

# Setup
title:    Онлайн казино - советы
tagline:  'blog'
description:  'Все советы о том как игарть в покер или онлайн казино'
url:    http://http://www.zvezda-langepasa.com
baseurl: "/"

author:
  name:   'Fishka'
  url:    http://www.zvezda-langepasa.com

paginate: 10

# Custom vars
icon:   /assets/images/icon.png
cover:    /assets/images/cover.jpg

menu:
  - title:  Home
    url:  /
    
copyright:
  author: Fishka
  url:    http://http://www.zvezda-langepasa.com
